# regression-qa/tests/test_cli.py
# Generated by regression-qa Generator
# Spec: regression-qa/specs/cli.md
from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from unittest.mock import MagicMock
from unittest.mock import patch

import pytest
from click.testing import CliRunner

from claudeplexer.cli import _load_vars
from claudeplexer.cli import _render
from claudeplexer.cli import _template_vars
from claudeplexer.cli import main


class TestTemplateVars:
    def test_empty_template(self):
        assert _template_vars("hello world") == set()

    def test_single_var(self):
        assert _template_vars("hello {{ name }}") == {"name"}

    def test_multiple_vars(self):
        result = _template_vars("{{ greeting }}, {{ name }}!")
        assert result == {"greeting", "name"}

    def test_no_vars(self):
        assert _template_vars("") == set()


class TestRender:
    def test_basic_render(self):
        result = _render("hello {{ name }}", {"name": "world"})
        assert result == "hello world"

    def test_multiple_vars(self):
        result = _render("{{ a }} and {{ b }}", {"a": "foo", "b": "bar"})
        assert result == "foo and bar"

    def test_missing_var_renders_empty(self):
        # Jinja2 default: undefined vars render as empty string
        result = _render("hello {{ name }}", {})
        assert result == "hello "


class TestLoadVars:
    def test_inline_json_array(self):
        data = [{"x": "1"}, {"x": "2"}]
        result = _load_vars(json.dumps(data), None)
        assert result == data

    def test_inline_non_array_raises(self):
        import click
        with pytest.raises(click.UsageError):
            _load_vars('{"x": "1"}', None)

    def test_file_json_array(self, tmp_path):
        data = [{"a": "hello"}, {"a": "world"}]
        f = tmp_path / "vars.json"
        f.write_text(json.dumps(data))
        result = _load_vars(None, str(f))
        assert result == data

    def test_file_jsonl(self, tmp_path):
        lines = [{"a": "hello"}, {"a": "world"}]
        f = tmp_path / "vars.jsonl"
        f.write_text("\n".join(json.dumps(d) for d in lines))
        result = _load_vars(None, str(f))
        assert result == lines


class TestMainValidation:
    def setup_method(self):
        self.runner = CliRunner()

    def test_prompts_and_template_mutually_exclusive(self):
        result = self.runner.invoke(main, ["hello", "--template", "{{ x }}"])
        assert result.exit_code != 0
        assert "Cannot combine" in result.output

    def test_vars_and_vars_file_mutually_exclusive(self, tmp_path):
        f = tmp_path / "v.json"
        f.write_text('[{"x": "1"}]')
        result = self.runner.invoke(
            main,
            ["--template", "{{ x }}", "--vars", '[{"x":"1"}]', "--vars-file", str(f)],
        )
        assert result.exit_code != 0
        assert "vars-file" in result.output or "vars" in result.output.lower()

    def test_vars_without_template_raises(self):
        result = self.runner.invoke(main, ["--vars", '[{"x":"1"}]'])
        assert result.exit_code != 0
        assert "requires --template" in result.output

    def test_template_without_vars_raises(self):
        result = self.runner.invoke(main, ["--template", "{{ x }}"])
        assert result.exit_code != 0
        assert "requires --vars" in result.output

    def test_no_args_raises(self):
        result = self.runner.invoke(main, [])
        assert result.exit_code != 0
        assert "Provide prompt" in result.output

    def test_missing_template_variable_raises(self):
        # template needs "name", vars dict omits it
        result = self.runner.invoke(
            main,
            ["--template", "hello {{ name }}", "--vars", '[{"x":"1"}]'],
        )
        assert result.exit_code != 0
        assert "missing variables" in result.output

    def test_extra_template_variable_raises(self):
        result = self.runner.invoke(
            main,
            ["--template", "hello {{ name }}", "--vars", '[{"name":"a","extra":"b"}]'],
        )
        assert result.exit_code != 0
        assert "unknown variables" in result.output


class TestMainLaunch:
    """Tests that exercise the _launch path. tmux subprocess calls are mocked."""

    def setup_method(self):
        self.runner = CliRunner()

    def _mock_tmux_ok(self):
        """Return a mock subprocess.run that always succeeds."""
        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = "test-session\n"
        mock_result.stderr = ""
        return mock_result

    def test_literal_prompts_no_session_no_tmux_raises(self):
        # No TMUX env var → _current_session() returns None → ClickException
        # Must patch os.environ directly; CliRunner's env kwarg does not affect
        # os.environ.get() calls inside the invoked command.
        clean_env = {k: v for k, v in os.environ.items() if k != "TMUX"}
        with patch.dict(os.environ, clean_env, clear=True):
            result = self.runner.invoke(main, ["hello world"])
        assert result.exit_code != 0
        assert "tmux session" in result.output.lower() or "Not inside" in result.output

    def test_prompts_exceed_max_raises(self):
        with patch("claudeplexer.cli.subprocess.run") as mock_run:
            mock_run.return_value = self._mock_tmux_ok()
            prompts = [f"prompt {i}" for i in range(12)]
            result = self.runner.invoke(main, prompts + ["--session", "test-sess", "--max", "10"])
        assert result.exit_code != 0
        assert "exceeds max" in result.output

    def test_literal_prompts_with_session(self):
        with patch("claudeplexer.cli.subprocess.run") as mock_run:
            mock_run.return_value = self._mock_tmux_ok()
            result = self.runner.invoke(main, ["hello", "world", "--session", "mysess"])
        assert result.exit_code == 0
        assert "Launched item-0" in result.output
        assert "Launched item-1" in result.output

    def test_template_with_inline_vars(self):
        with patch("claudeplexer.cli.subprocess.run") as mock_run:
            mock_run.return_value = self._mock_tmux_ok()
            result = self.runner.invoke(
                main,
                [
                    "--template", "hello {{ name }}",
                    "--vars", '[{"name":"alice"},{"name":"bob"}]',
                    "--session", "mysess",
                ],
            )
        assert result.exit_code == 0
        assert "Launched item-0" in result.output
        assert "Launched item-1" in result.output

    def test_template_with_vars_file_json_array(self, tmp_path):
        f = tmp_path / "vars.json"
        f.write_text('[{"name":"alice"},{"name":"bob"}]')
        with patch("claudeplexer.cli.subprocess.run") as mock_run:
            mock_run.return_value = self._mock_tmux_ok()
            result = self.runner.invoke(
                main,
                [
                    "--template", "hello {{ name }}",
                    "--vars-file", str(f),
                    "--session", "mysess",
                ],
            )
        assert result.exit_code == 0
        assert "Launched item-0" in result.output
        assert "Launched item-1" in result.output

    def test_template_with_vars_file_jsonl(self, tmp_path):
        f = tmp_path / "vars.jsonl"
        f.write_text('{"name":"alice"}\n{"name":"bob"}')
        with patch("claudeplexer.cli.subprocess.run") as mock_run:
            mock_run.return_value = self._mock_tmux_ok()
            result = self.runner.invoke(
                main,
                [
                    "--template", "hello {{ name }}",
                    "--vars-file", str(f),
                    "--session", "mysess",
                ],
            )
        assert result.exit_code == 0
        assert "Launched item-0" in result.output
        assert "Launched item-1" in result.output

    def test_session_creation_fails_raises(self):
        mock_fail = MagicMock()
        mock_fail.returncode = 1
        mock_fail.stderr = "duplicate session"
        with patch("claudeplexer.cli.subprocess.run", return_value=mock_fail):
            result = self.runner.invoke(main, ["hello", "--session", "existing"])
        assert result.exit_code != 0
        assert "Failed to create session" in result.output

    def test_window_creation_fails_raises(self):
        call_count = 0

        def side_effect(*args, **kwargs):
            nonlocal call_count
            call_count += 1
            m = MagicMock()
            # First call: tmux new-session succeeds; second: new-window fails
            if call_count == 1:
                m.returncode = 0
                m.stderr = ""
            else:
                m.returncode = 1
                m.stderr = "window error"
            return m

        with patch("claudeplexer.cli.subprocess.run", side_effect=side_effect):
            result = self.runner.invoke(main, ["hello", "--session", "mysess"])
        assert result.exit_code != 0
        assert "Failed to create window" in result.output
